### PR TITLE
Development

### PR DESCRIPTION
**Pull request by notsilverhoft**
I fixed all of the issues with c2man using another Debian docker container and added a main script to build everything. I added some arguments to help with debugging.

### CODE REVIEW

**Comment by VitoVan** [comment]
Since [this line](https://github.com/VitoVan/pango-cairo-wasm/pull/7/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823L221) was removed, it will fail the building of c2man on Fedora as well.

If this PR were merged, it will break the building process on Fedora, and it still might have problem on Debian.

**Comment by notsilverhoft** [comment]
Yes, you are correct, I will add a condition to fix this

**Comment by notsilverhoft** [comment]
I added the condition, for this PR I am fixing the c2man issue on docker, I can start working on fixing the native builds, and create a build script for Debian if you would like.

**Comment by VitoVan** [comment]
No, sir.

Adding an variable `$USINGDOCKER` shouldn't be count as a "fix".

I started to wonder if I was talking to an AI chatbot. Correct me if I were mistaken.

**Comment by VitoVan** [comment]
I suggest that any further development be fully discussed beforehand to avoid wasting your time.

**Comment by notsilverhoft** [comment]
> No, sir.
> 
> Adding an variable `$USINGDOCKER` shouldn't be count as a "fix".
> 
> I started to wonder if I was talking to an AI chatbot. Correct me if I were mistaken.

You are being corrected, please explain what exactly you would like to do, I attempted to run a docker build in the current build, due to the fact that docker does not permit the use of systemd or dockerd, it is impossible to run both docker scripts at once.

**Comment by VitoVan** [comment]
> You are being corrected

I'm sorry for this misunderstanding, thanks for your clarification.

> please explain what exactly you would like to do

This script should work well on Debian using Docker, and should work well natively on Fedora.

So, if we are trying to modify anything, we should firstly ensure that 1) we don't break anything, 2) we don't solve anything which was already solved by using docker.

And I would like to keep this script as it is if the improvements break old things and add little value for new features.

**Comment by VitoVan** [comment]
> This script should work well on Debian using Docker, and should work well natively on Fedora.

I'm sorry, my fault, it seems the current code failed to build on current Fedora as well, due to the problem caused by c2man.

https://github.com/VitoVan/pango-cairo-wasm/actions/runs/11756336008/job/32752377759#step:7:9800

**Comment by VitoVan** [comment]
Due to the old age of c2man, I have to fix the system version to Fedora 38.

The problem was fixed by 7e1372dd85ec55bc2a14e8ff38dc0ed55b8f772c

**Comment by VitoVan** [comment]
I'm closing this PR, because it doesn't fit the newly added contributing guide:

https://github.com/VitoVan/pango-cairo-wasm?tab=readme-ov-file#contributing

I'm sorry if you think I'm being a bad person.

But, anyway, thanks for your work.

**Pull request closed without merging**
