### PR TITLE
Fixed paths

### PR DESCRIPTION
**Pull request by notsilverhoft**
Fixed some simple path issues

### CODE REVIEW

**Comment by VitoVan** [comment]
@notsilverhoft Hi there, may I know what issues you have encountered with the original code? In what situation?

**Comment by notsilverhoft** [comment]
I am trying to use this in a Debian based distribution, and it was unable to find the path, the way I did it was without docker, and when I did change it, it worked in both docker, and regular bash. Idk, I just thought It might make things a little easier.

**Comment by notsilverhoft** [comment]
Also I am about to do another dev run with docker, but I have some issues that have been coming up with Pango(And Fribidi) specifically, I will open an issue if this one doesn't work.

**Comment by VitoVan** [comment]
Thank you, since it's just 1 modification, but with 8 commits, I will squash and merge this.

And then go reading your another issue.

**Pull request merged**
